### ISSUE TITLE
按照你之前的文章使用Travis CI对blog进行部署，没有成功，请教一下问题在哪里

### ISSUE THREAD

**Issue by ghost** [Troy-Yang/troy-yang.github.io#1]
[传送门在此](https://github.com/lzq920/lzq920.github.io/tree/master)

**Comment by Troy-Yang** [comment]
比较了一下你的travis.yml文件，似乎看起来没有问题，和我的几乎一样，不过请确认你的Github_TOKEN值是否配置好，大小写是否正确，还有，登录你的https://travis-ci.org ，看看有没有配置好，配置确认没问题后，在提交代码再看看输出console日志是什么内容，上面能看到具体错误信息。

**Comment by ghost** [comment]
找到原因了。因为我提交源码的时候主题里面把配置文件给忽略了。。。。
